import type { Metadata } from "next";

import "./globals.css";
import { Geist } from "next/font/google";

import { TooltipProvider } from "@/components/ui/tooltip";
import { cn } from "@/lib/utils";

const geist = Geist({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  description: "Generated by create-vinext-app",
  title: "vinext on Cloudflare Workers",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={cn("font-sans", geist.variable)}>
      <TooltipProvider>
        <body>{children}</body>
      </TooltipProvider>
    </html>
  );
}
